// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6D_iO_wkR8K29xJblAOrpHOIpmybjWZ0',
    appId: '1:158348524257:web:acc5cc3774a0ae61b5d5a0',
    messagingSenderId: '158348524257',
    projectId: 'xianinfotech-b0217',
    authDomain: 'xianinfotech-b0217.firebaseapp.com',
    storageBucket: 'xianinfotech-b0217.appspot.com',
    measurementId: 'G-0QZS1HC0S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGl78GgW2CmiZpkYk2Uf9NAu8eRXo25Q',
    appId: '1:158348524257:android:77d7f50920d6552cb5d5a0',
    messagingSenderId: '158348524257',
    projectId: 'xianinfotech-b0217',
    storageBucket: 'xianinfotech-b0217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbWQZ8s3TchS0NkIvC74ZPNqT80x9v5I',
    appId: '1:158348524257:ios:9f9da21b53453d65b5d5a0',
    messagingSenderId: '158348524257',
    projectId: 'xianinfotech-b0217',
    storageBucket: 'xianinfotech-b0217.appspot.com',
    iosBundleId: 'com.example.xianinfotechInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbWQZ8s3TchS0NkIvC74ZPNqT80x9v5I',
    appId: '1:158348524257:ios:9f9da21b53453d65b5d5a0',
    messagingSenderId: '158348524257',
    projectId: 'xianinfotech-b0217',
    storageBucket: 'xianinfotech-b0217.appspot.com',
    iosBundleId: 'com.example.xianinfotechInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6D_iO_wkR8K29xJblAOrpHOIpmybjWZ0',
    appId: '1:158348524257:web:fdb2e7b6fcdd4762b5d5a0',
    messagingSenderId: '158348524257',
    projectId: 'xianinfotech-b0217',
    authDomain: 'xianinfotech-b0217.firebaseapp.com',
    storageBucket: 'xianinfotech-b0217.appspot.com',
    measurementId: 'G-G2Y6B8M7Q2',
  );
}
